version: "3.7"
services:
  database:
    container_name: app_db
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=test123!
      - POSTGRES_DB=postgres_app
      - POSTGRES_PORT=5432
    ports:
      - 5432
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgresdata:/var/lib/postgresql/data
    networks:
      - gameconsole
  service:
    build:
      context: ./service
      dockerfile: dockerfile
    depends_on:
      - database
    networks:
      - gameconsole
    ports:
      - "8080:8080"
    environment:
      POSTGRES_HOST: database
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test123!
      POSTGRES_DB: postgres_app
networks:
  gameconsole:
    name: gameconsole
